/* Export a balanced slice of the production question pool into
 * supabase/seed.sql so the LOCAL stack (and CI) can assemble full adaptive
 * tests. Run against PROD env (deliberate, read-only):
 *   pnpm dlx tsx --env-file=.env.operator-prod scripts/export-seed.ts
 *
 * Slice: per (section, skill, difficulty) up to PER_CELL enabled questions,
 * newest first — enough for full-test module composition (27 rw / 22 math per
 * module, 9/9/9 module-1 mix) plus drills, small enough to commit (~1 MB).
 */
import { writeFileSync } from 'node:fs';
import { createClient } from '@supabase/supabase-js';

const PER_CELL = 6;

const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!url || !key) throw new Error('needs prod NEXT_PUBLIC_SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY');

const q = (v: unknown): string => {
  if (v === null || v === undefined) return 'null';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  const s = typeof v === 'string' ? v : JSON.stringify(v);
  return `'${s.replace(/'/g, "''")}'`;
};

async function main() {
  const db = createClient(url!, key!, { auth: { persistSession: false } });
  const cols =
    'id, section, skill, passage, prompt, choices, answer_index, explanation, source, enabled, difficulty, difficulty_source, response_format, correct_answer, answer_tolerance, figure, review_status, dedup_hash';

  const picked: Record<string, unknown>[] = [];
  const sections = ['rw', 'math'] as const;
  const difficulties = ['easy', 'medium', 'hard'] as const;

  for (const section of sections) {
    // Enumerate skills present in prod for this section.
    const { data: skillsRows, error: sErr } = await db
      .schema('sat')
      .from('questions')
      .select('skill')
      .eq('section', section)
      .eq('enabled', true)
      .limit(10000);
    if (sErr) throw sErr;
    const skills = [...new Set((skillsRows ?? []).map((r: { skill: string }) => r.skill))];

    for (const skill of skills) {
      for (const difficulty of difficulties) {
        const { data, error } = await db
          .schema('sat')
          .from('questions')
          .select(cols)
          .eq('section', section)
          .eq('skill', skill)
          .eq('difficulty', difficulty)
          .eq('enabled', true)
          .eq('review_status', 'active')
          .order('created_at', { ascending: false })
          .limit(PER_CELL);
        if (error) throw error;
        picked.push(...((data ?? []) as Record<string, unknown>[]));
      }
    }
  }

  const lines = [
    '-- Generated by scripts/export-seed.ts — a balanced slice of the prod',
    '-- question pool for the LOCAL stack + CI. Regenerate any time with:',
    '--   pnpm dlx tsx --env-file=.env.operator-prod scripts/export-seed.ts',
    `-- ${picked.length} questions, up to ${PER_CELL} per (section, skill, difficulty).`,
    '',
  ];
  for (const r of picked) {
    lines.push(
      'insert into sat.questions (id, section, skill, passage, prompt, choices, answer_index, explanation, source, enabled, difficulty, difficulty_source, response_format, correct_answer, answer_tolerance, figure, review_status, dedup_hash) values (' +
        [
          q(r.id), q(r.section), q(r.skill), q(r.passage), q(r.prompt),
          q(r.choices) + '::jsonb', q(r.answer_index), q(r.explanation),
          q(r.source), q(r.enabled), q(r.difficulty), q(r.difficulty_source),
          q(r.response_format), q(r.correct_answer), q(r.answer_tolerance),
          r.figure === null ? 'null' : q(r.figure) + '::jsonb',
          q(r.review_status), q(r.dedup_hash),
        ].join(', ') +
        ') on conflict (id) do nothing;',
    );
  }
  writeFileSync('supabase/seed.sql', lines.join('\n') + '\n', 'utf8');

  const bySec: Record<string, number> = {};
  for (const r of picked) bySec[r.section as string] = (bySec[r.section as string] ?? 0) + 1;
  console.log(`wrote supabase/seed.sql: ${picked.length} questions`, bySec);
}

main();
